### ISSUE TITLE
How long do we wanna make it?

### ISSUE THREAD

**Issue by stevenpitts** [makusu2/code-jam-5#25]
Like, the idea of a clicker is the grind, but we don't want the judges to have to stream themselves clicking a lot... or maybe we could keep the grind, but include enough jokes scattered about that it never gets boring?
Thoughts?

**Comment by missingfragment** [comment]
I think it should be considerably less grindy than a regular clicker game, maybe just enough that there's a sense of progression.  What we could do is make the upgrades have high costs but very powerful effects, so like maybe you need 500 clicks to get solar panels but they give tons of points per second so after that you don't have to click as much.  Also I think some one-time upgrades would be cool.

**Comment by Foknetics** [comment]
If we’re looking for an end point we could use the worlds energy consumption. Seems to be around 15 terawatts per day. We’d have to play with units and things to figure out how to make that reasonable but effectively once you got to that much per day with a combination of clicking and machines you would “win” because the world would be free of fossil fuel powered energy gen

**Comment by stevenpitts** [comment]
> If we’re looking for an end point we could use the worlds energy consumption. Seems to be around 15 terawatts per day. We’d have to play with units and things to figure out how to make that reasonable but effectively once you got to that much per day with a combination of clicking and machines you would “win” because the world would be free of fossil fuel powered energy gen

!!!!!!!! That's a really good idea!

**Comment by stevenpitts** [comment]
Closing as the code jam is over
